// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const areaBreakdownByChild = `-- name: AreaBreakdownByChild :many
SELECT a.cognitive_area, count(*) AS interaction_count
FROM interaction_analysis a
JOIN interactions i ON i.id = a.interaction_id
WHERE i.child_id = $1 AND a.cognitive_area <> ''
GROUP BY a.cognitive_area
ORDER BY interaction_count DESC
`

type AreaBreakdownByChildRow struct {
	CognitiveArea    string `json:"cognitive_area"`
	InteractionCount int64  `json:"interaction_count"`
}

// Development by cognitive area (counts per area).
func (q *Queries) AreaBreakdownByChild(ctx context.Context, childID pgtype.UUID) ([]AreaBreakdownByChildRow, error) {
	rows, err := q.db.Query(ctx, areaBreakdownByChild, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AreaBreakdownByChildRow
	for rows.Next() {
		var i AreaBreakdownByChildRow
		if err := rows.Scan(&i.CognitiveArea, &i.InteractionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bumpChildTopicStat = `-- name: BumpChildTopicStat :exec
INSERT INTO child_topic_stats (child_id, topic_id, interaction_count, first_seen_at, last_seen_at)
VALUES ($1, $2, 1, now(), now())
ON CONFLICT (child_id, topic_id) DO UPDATE
SET interaction_count = child_topic_stats.interaction_count + 1,
    last_seen_at = now()
`

type BumpChildTopicStatParams struct {
	ChildID uuid.UUID `json:"child_id"`
	TopicID uuid.UUID `json:"topic_id"`
}

func (q *Queries) BumpChildTopicStat(ctx context.Context, arg BumpChildTopicStatParams) error {
	_, err := q.db.Exec(ctx, bumpChildTopicStat, arg.ChildID, arg.TopicID)
	return err
}

const createRecommendation = `-- name: CreateRecommendation :one
INSERT INTO recommendations (child_id, topic_id, area, title, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, child_id, topic_id, area, title, body, status, generated_at
`

type CreateRecommendationParams struct {
	ChildID uuid.UUID   `json:"child_id"`
	TopicID pgtype.UUID `json:"topic_id"`
	Area    string      `json:"area"`
	Title   string      `json:"title"`
	Body    string      `json:"body"`
}

func (q *Queries) CreateRecommendation(ctx context.Context, arg CreateRecommendationParams) (Recommendation, error) {
	row := q.db.QueryRow(ctx, createRecommendation,
		arg.ChildID,
		arg.TopicID,
		arg.Area,
		arg.Title,
		arg.Body,
	)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.TopicID,
		&i.Area,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.GeneratedAt,
	)
	return i, err
}

const linkInteractionTopic = `-- name: LinkInteractionTopic :exec
INSERT INTO interaction_topics (interaction_id, topic_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkInteractionTopicParams struct {
	InteractionID uuid.UUID `json:"interaction_id"`
	TopicID       uuid.UUID `json:"topic_id"`
}

func (q *Queries) LinkInteractionTopic(ctx context.Context, arg LinkInteractionTopicParams) error {
	_, err := q.db.Exec(ctx, linkInteractionTopic, arg.InteractionID, arg.TopicID)
	return err
}

const listChildTopicGraph = `-- name: ListChildTopicGraph :many
SELECT t.id, t.slug, t.label, t.area, t.parent_id,
       s.interaction_count, s.last_seen_at
FROM child_topic_stats s
JOIN topics t ON t.id = s.topic_id
WHERE s.child_id = $1
ORDER BY s.interaction_count DESC
`

type ListChildTopicGraphRow struct {
	ID               uuid.UUID   `json:"id"`
	Slug             string      `json:"slug"`
	Label            string      `json:"label"`
	Area             string      `json:"area"`
	ParentID         pgtype.UUID `json:"parent_id"`
	InteractionCount int32       `json:"interaction_count"`
	LastSeenAt       time.Time   `json:"last_seen_at"`
}

// Interest-graph nodes: each topic the child engaged with + frequency.
func (q *Queries) ListChildTopicGraph(ctx context.Context, childID uuid.UUID) ([]ListChildTopicGraphRow, error) {
	rows, err := q.db.Query(ctx, listChildTopicGraph, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildTopicGraphRow
	for rows.Next() {
		var i ListChildTopicGraphRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Label,
			&i.Area,
			&i.ParentID,
			&i.InteractionCount,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendationsByChild = `-- name: ListRecommendationsByChild :many
SELECT id, child_id, topic_id, area, title, body, status, generated_at FROM recommendations
WHERE child_id = $1 AND status <> 'dismissed'
ORDER BY generated_at DESC
`

func (q *Queries) ListRecommendationsByChild(ctx context.Context, childID uuid.UUID) ([]Recommendation, error) {
	rows, err := q.db.Query(ctx, listRecommendationsByChild, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recommendation
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.TopicID,
			&i.Area,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInteractionAnalysis = `-- name: UpsertInteractionAnalysis :one
INSERT INTO interaction_analysis (
    interaction_id, cognitive_area, question_type, complexity_level, sentiment, model
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (interaction_id) DO UPDATE
SET cognitive_area = EXCLUDED.cognitive_area,
    question_type = EXCLUDED.question_type,
    complexity_level = EXCLUDED.complexity_level,
    sentiment = EXCLUDED.sentiment,
    model = EXCLUDED.model,
    analyzed_at = now()
RETURNING interaction_id, cognitive_area, question_type, complexity_level, sentiment, model, analyzed_at
`

type UpsertInteractionAnalysisParams struct {
	InteractionID   uuid.UUID `json:"interaction_id"`
	CognitiveArea   string    `json:"cognitive_area"`
	QuestionType    string    `json:"question_type"`
	ComplexityLevel int16     `json:"complexity_level"`
	Sentiment       string    `json:"sentiment"`
	Model           string    `json:"model"`
}

func (q *Queries) UpsertInteractionAnalysis(ctx context.Context, arg UpsertInteractionAnalysisParams) (InteractionAnalysis, error) {
	row := q.db.QueryRow(ctx, upsertInteractionAnalysis,
		arg.InteractionID,
		arg.CognitiveArea,
		arg.QuestionType,
		arg.ComplexityLevel,
		arg.Sentiment,
		arg.Model,
	)
	var i InteractionAnalysis
	err := row.Scan(
		&i.InteractionID,
		&i.CognitiveArea,
		&i.QuestionType,
		&i.ComplexityLevel,
		&i.Sentiment,
		&i.Model,
		&i.AnalyzedAt,
	)
	return i, err
}

const upsertTopic = `-- name: UpsertTopic :one
INSERT INTO topics (slug, label, area)
VALUES ($1, $2, $3)
ON CONFLICT (slug) DO UPDATE SET label = EXCLUDED.label
RETURNING id, slug, label, parent_id, area
`

type UpsertTopicParams struct {
	Slug  string `json:"slug"`
	Label string `json:"label"`
	Area  string `json:"area"`
}

func (q *Queries) UpsertTopic(ctx context.Context, arg UpsertTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, upsertTopic, arg.Slug, arg.Label, arg.Area)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Label,
		&i.ParentID,
		&i.Area,
	)
	return i, err
}
