// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: children.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignDevice = `-- name: AssignDevice :one
INSERT INTO device_assignments (device_id, child_id)
VALUES ($1, $2)
RETURNING id, device_id, child_id, active, assigned_at, unassigned_at
`

type AssignDeviceParams struct {
	DeviceID uuid.UUID `json:"device_id"`
	ChildID  uuid.UUID `json:"child_id"`
}

// Deactivate any current assignment for this device, then create the new one.
// (Run inside a tx with DeactivateDeviceAssignments first.)
func (q *Queries) AssignDevice(ctx context.Context, arg AssignDeviceParams) (DeviceAssignment, error) {
	row := q.db.QueryRow(ctx, assignDevice, arg.DeviceID, arg.ChildID)
	var i DeviceAssignment
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.ChildID,
		&i.Active,
		&i.AssignedAt,
		&i.UnassignedAt,
	)
	return i, err
}

const createChild = `-- name: CreateChild :one
INSERT INTO children (account_id, name, birthdate, avatar)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, name, birthdate, avatar, created_at
`

type CreateChildParams struct {
	AccountID uuid.UUID   `json:"account_id"`
	Name      string      `json:"name"`
	Birthdate pgtype.Date `json:"birthdate"`
	Avatar    string      `json:"avatar"`
}

func (q *Queries) CreateChild(ctx context.Context, arg CreateChildParams) (Child, error) {
	row := q.db.QueryRow(ctx, createChild,
		arg.AccountID,
		arg.Name,
		arg.Birthdate,
		arg.Avatar,
	)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Birthdate,
		&i.Avatar,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateDeviceAssignments = `-- name: DeactivateDeviceAssignments :exec
UPDATE device_assignments
SET active = false, unassigned_at = now()
WHERE device_id = $1 AND active
`

func (q *Queries) DeactivateDeviceAssignments(ctx context.Context, deviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateDeviceAssignments, deviceID)
	return err
}

const getActiveChildForDevice = `-- name: GetActiveChildForDevice :one
SELECT c.id, c.account_id, c.name, c.birthdate, c.avatar, c.created_at
FROM device_assignments da
JOIN children c ON c.id = da.child_id
WHERE da.device_id = $1 AND da.active
`

// Resolve device -> active child (used by the MQTT ingest for attribution).
func (q *Queries) GetActiveChildForDevice(ctx context.Context, deviceID uuid.UUID) (Child, error) {
	row := q.db.QueryRow(ctx, getActiveChildForDevice, deviceID)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Birthdate,
		&i.Avatar,
		&i.CreatedAt,
	)
	return i, err
}

const getChild = `-- name: GetChild :one
SELECT id, account_id, name, birthdate, avatar, created_at FROM children WHERE id = $1
`

func (q *Queries) GetChild(ctx context.Context, id uuid.UUID) (Child, error) {
	row := q.db.QueryRow(ctx, getChild, id)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Birthdate,
		&i.Avatar,
		&i.CreatedAt,
	)
	return i, err
}

const listChildrenByAccount = `-- name: ListChildrenByAccount :many
SELECT id, account_id, name, birthdate, avatar, created_at FROM children WHERE account_id = $1 ORDER BY created_at
`

func (q *Queries) ListChildrenByAccount(ctx context.Context, accountID uuid.UUID) ([]Child, error) {
	rows, err := q.db.Query(ctx, listChildrenByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Child
	for rows.Next() {
		var i Child
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Birthdate,
			&i.Avatar,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
