// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDevice = `-- name: ClaimDevice :one
UPDATE devices
SET account_id = $2,
    mqtt_username = $3,
    mqtt_password_hash = $4,
    claimed_at = now()
WHERE id = $1 AND account_id IS NULL
RETURNING id, name, created_at, serial_number, activation_code_hash, account_id, mqtt_username, mqtt_password_hash, firmware_version, last_seen_at, claimed_at
`

type ClaimDeviceParams struct {
	ID               uuid.UUID   `json:"id"`
	AccountID        pgtype.UUID `json:"account_id"`
	MqttUsername     *string     `json:"mqtt_username"`
	MqttPasswordHash *string     `json:"mqtt_password_hash"`
}

// Bind an unclaimed device to an account and provision its MQTT credentials.
func (q *Queries) ClaimDevice(ctx context.Context, arg ClaimDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, claimDevice,
		arg.ID,
		arg.AccountID,
		arg.MqttUsername,
		arg.MqttPasswordHash,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.SerialNumber,
		&i.ActivationCodeHash,
		&i.AccountID,
		&i.MqttUsername,
		&i.MqttPasswordHash,
		&i.FirmwareVersion,
		&i.LastSeenAt,
		&i.ClaimedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, name, created_at, serial_number, activation_code_hash, account_id, mqtt_username, mqtt_password_hash, firmware_version, last_seen_at, claimed_at FROM devices WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.SerialNumber,
		&i.ActivationCodeHash,
		&i.AccountID,
		&i.MqttUsername,
		&i.MqttPasswordHash,
		&i.FirmwareVersion,
		&i.LastSeenAt,
		&i.ClaimedAt,
	)
	return i, err
}

const getDeviceBySerial = `-- name: GetDeviceBySerial :one
SELECT id, name, created_at, serial_number, activation_code_hash, account_id, mqtt_username, mqtt_password_hash, firmware_version, last_seen_at, claimed_at FROM devices WHERE serial_number = $1
`

func (q *Queries) GetDeviceBySerial(ctx context.Context, serialNumber *string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceBySerial, serialNumber)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.SerialNumber,
		&i.ActivationCodeHash,
		&i.AccountID,
		&i.MqttUsername,
		&i.MqttPasswordHash,
		&i.FirmwareVersion,
		&i.LastSeenAt,
		&i.ClaimedAt,
	)
	return i, err
}

const listDevicesByAccount = `-- name: ListDevicesByAccount :many
SELECT id, name, created_at, serial_number, activation_code_hash, account_id, mqtt_username, mqtt_password_hash, firmware_version, last_seen_at, claimed_at FROM devices WHERE account_id = $1 ORDER BY claimed_at DESC
`

func (q *Queries) ListDevicesByAccount(ctx context.Context, accountID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.SerialNumber,
			&i.ActivationCodeHash,
			&i.AccountID,
			&i.MqttUsername,
			&i.MqttPasswordHash,
			&i.FirmwareVersion,
			&i.LastSeenAt,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedDevice = `-- name: SeedDevice :one
INSERT INTO devices (serial_number, activation_code_hash, name)
VALUES ($1, $2, $3)
RETURNING id, name, created_at, serial_number, activation_code_hash, account_id, mqtt_username, mqtt_password_hash, firmware_version, last_seen_at, claimed_at
`

type SeedDeviceParams struct {
	SerialNumber       *string `json:"serial_number"`
	ActivationCodeHash *string `json:"activation_code_hash"`
	Name               string  `json:"name"`
}

// Factory provisioning: create an unclaimed device with a serial + activation hash.
func (q *Queries) SeedDevice(ctx context.Context, arg SeedDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, seedDevice, arg.SerialNumber, arg.ActivationCodeHash, arg.Name)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.SerialNumber,
		&i.ActivationCodeHash,
		&i.AccountID,
		&i.MqttUsername,
		&i.MqttPasswordHash,
		&i.FirmwareVersion,
		&i.LastSeenAt,
		&i.ClaimedAt,
	)
	return i, err
}

const touchDeviceLastSeen = `-- name: TouchDeviceLastSeen :exec
UPDATE devices SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchDeviceLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchDeviceLastSeen, id)
	return err
}
