// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interactions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const childUsageByHour = `-- name: ChildUsageByHour :many
SELECT
    date_trunc('hour', created_at) AS bucket,
    count(*)                       AS interaction_count
FROM interactions
WHERE child_id = $1 AND created_at >= $2 AND created_at < $3
GROUP BY bucket
ORDER BY bucket
`

type ChildUsageByHourParams struct {
	ChildID     pgtype.UUID `json:"child_id"`
	CreatedAt   time.Time   `json:"created_at"`
	CreatedAt_2 time.Time   `json:"created_at_2"`
}

type ChildUsageByHourRow struct {
	Bucket           pgtype.Interval `json:"bucket"`
	InteractionCount int64           `json:"interaction_count"`
}

// Days x hours usage for the dashboard heatmap.
func (q *Queries) ChildUsageByHour(ctx context.Context, arg ChildUsageByHourParams) ([]ChildUsageByHourRow, error) {
	rows, err := q.db.Query(ctx, childUsageByHour, arg.ChildID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChildUsageByHourRow
	for rows.Next() {
		var i ChildUsageByHourRow
		if err := rows.Scan(&i.Bucket, &i.InteractionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createInteraction = `-- name: CreateInteraction :one
INSERT INTO interactions (
    device_id, child_id, session_id, transcript, response_text,
    stt_latency_ms, llm_latency_ms, tts_latency_ms, total_latency_ms,
    llm_model, llm_tokens_in, llm_tokens_out
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, device_id, transcript, response_text, stt_latency_ms, llm_latency_ms, tts_latency_ms, total_latency_ms, llm_model, llm_tokens_in, llm_tokens_out, created_at, child_id, session_id
`

type CreateInteractionParams struct {
	DeviceID       uuid.UUID   `json:"device_id"`
	ChildID        pgtype.UUID `json:"child_id"`
	SessionID      pgtype.UUID `json:"session_id"`
	Transcript     string      `json:"transcript"`
	ResponseText   string      `json:"response_text"`
	SttLatencyMs   int32       `json:"stt_latency_ms"`
	LlmLatencyMs   int32       `json:"llm_latency_ms"`
	TtsLatencyMs   int32       `json:"tts_latency_ms"`
	TotalLatencyMs int32       `json:"total_latency_ms"`
	LlmModel       string      `json:"llm_model"`
	LlmTokensIn    int32       `json:"llm_tokens_in"`
	LlmTokensOut   int32       `json:"llm_tokens_out"`
}

func (q *Queries) CreateInteraction(ctx context.Context, arg CreateInteractionParams) (Interaction, error) {
	row := q.db.QueryRow(ctx, createInteraction,
		arg.DeviceID,
		arg.ChildID,
		arg.SessionID,
		arg.Transcript,
		arg.ResponseText,
		arg.SttLatencyMs,
		arg.LlmLatencyMs,
		arg.TtsLatencyMs,
		arg.TotalLatencyMs,
		arg.LlmModel,
		arg.LlmTokensIn,
		arg.LlmTokensOut,
	)
	var i Interaction
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Transcript,
		&i.ResponseText,
		&i.SttLatencyMs,
		&i.LlmLatencyMs,
		&i.TtsLatencyMs,
		&i.TotalLatencyMs,
		&i.LlmModel,
		&i.LlmTokensIn,
		&i.LlmTokensOut,
		&i.CreatedAt,
		&i.ChildID,
		&i.SessionID,
	)
	return i, err
}

const getInteraction = `-- name: GetInteraction :one
SELECT id, device_id, transcript, response_text, stt_latency_ms, llm_latency_ms, tts_latency_ms, total_latency_ms, llm_model, llm_tokens_in, llm_tokens_out, created_at, child_id, session_id FROM interactions WHERE id = $1
`

func (q *Queries) GetInteraction(ctx context.Context, id uuid.UUID) (Interaction, error) {
	row := q.db.QueryRow(ctx, getInteraction, id)
	var i Interaction
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Transcript,
		&i.ResponseText,
		&i.SttLatencyMs,
		&i.LlmLatencyMs,
		&i.TtsLatencyMs,
		&i.TotalLatencyMs,
		&i.LlmModel,
		&i.LlmTokensIn,
		&i.LlmTokensOut,
		&i.CreatedAt,
		&i.ChildID,
		&i.SessionID,
	)
	return i, err
}

const listInteractionsByChild = `-- name: ListInteractionsByChild :many
SELECT id, device_id, transcript, response_text, stt_latency_ms, llm_latency_ms, tts_latency_ms, total_latency_ms, llm_model, llm_tokens_in, llm_tokens_out, created_at, child_id, session_id FROM interactions
WHERE child_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListInteractionsByChildParams struct {
	ChildID pgtype.UUID `json:"child_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListInteractionsByChild(ctx context.Context, arg ListInteractionsByChildParams) ([]Interaction, error) {
	rows, err := q.db.Query(ctx, listInteractionsByChild, arg.ChildID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Interaction
	for rows.Next() {
		var i Interaction
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Transcript,
			&i.ResponseText,
			&i.SttLatencyMs,
			&i.LlmLatencyMs,
			&i.TtsLatencyMs,
			&i.TotalLatencyMs,
			&i.LlmModel,
			&i.LlmTokensIn,
			&i.LlmTokensOut,
			&i.CreatedAt,
			&i.ChildID,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnanalyzedInteractions = `-- name: ListUnanalyzedInteractions :many
SELECT i.id, i.device_id, i.transcript, i.response_text, i.stt_latency_ms, i.llm_latency_ms, i.tts_latency_ms, i.total_latency_ms, i.llm_model, i.llm_tokens_in, i.llm_tokens_out, i.created_at, i.child_id, i.session_id FROM interactions i
LEFT JOIN interaction_analysis a ON a.interaction_id = i.id
WHERE a.interaction_id IS NULL
ORDER BY i.created_at
LIMIT $1
`

// Feeds the analysis worker: interactions without an analysis row yet.
func (q *Queries) ListUnanalyzedInteractions(ctx context.Context, limit int32) ([]Interaction, error) {
	rows, err := q.db.Query(ctx, listUnanalyzedInteractions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Interaction
	for rows.Next() {
		var i Interaction
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Transcript,
			&i.ResponseText,
			&i.SttLatencyMs,
			&i.LlmLatencyMs,
			&i.TtsLatencyMs,
			&i.TotalLatencyMs,
			&i.LlmModel,
			&i.LlmTokensIn,
			&i.LlmTokensOut,
			&i.CreatedAt,
			&i.ChildID,
			&i.SessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
