// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	FullName     string    `json:"full_name"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Child struct {
	ID        uuid.UUID   `json:"id"`
	AccountID uuid.UUID   `json:"account_id"`
	Name      string      `json:"name"`
	Birthdate pgtype.Date `json:"birthdate"`
	Avatar    string      `json:"avatar"`
	CreatedAt time.Time   `json:"created_at"`
}

type ChildTopicStat struct {
	ChildID          uuid.UUID `json:"child_id"`
	TopicID          uuid.UUID `json:"topic_id"`
	InteractionCount int32     `json:"interaction_count"`
	FirstSeenAt      time.Time `json:"first_seen_at"`
	LastSeenAt       time.Time `json:"last_seen_at"`
}

type Device struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	CreatedAt          time.Time          `json:"created_at"`
	SerialNumber       *string            `json:"serial_number"`
	ActivationCodeHash *string            `json:"activation_code_hash"`
	AccountID          pgtype.UUID        `json:"account_id"`
	MqttUsername       *string            `json:"mqtt_username"`
	MqttPasswordHash   *string            `json:"mqtt_password_hash"`
	FirmwareVersion    string             `json:"firmware_version"`
	LastSeenAt         pgtype.Timestamptz `json:"last_seen_at"`
	ClaimedAt          pgtype.Timestamptz `json:"claimed_at"`
}

type DeviceAssignment struct {
	ID           uuid.UUID          `json:"id"`
	DeviceID     uuid.UUID          `json:"device_id"`
	ChildID      uuid.UUID          `json:"child_id"`
	Active       bool               `json:"active"`
	AssignedAt   time.Time          `json:"assigned_at"`
	UnassignedAt pgtype.Timestamptz `json:"unassigned_at"`
}

type Interaction struct {
	ID             uuid.UUID   `json:"id"`
	DeviceID       uuid.UUID   `json:"device_id"`
	Transcript     string      `json:"transcript"`
	ResponseText   string      `json:"response_text"`
	SttLatencyMs   int32       `json:"stt_latency_ms"`
	LlmLatencyMs   int32       `json:"llm_latency_ms"`
	TtsLatencyMs   int32       `json:"tts_latency_ms"`
	TotalLatencyMs int32       `json:"total_latency_ms"`
	LlmModel       string      `json:"llm_model"`
	LlmTokensIn    int32       `json:"llm_tokens_in"`
	LlmTokensOut   int32       `json:"llm_tokens_out"`
	CreatedAt      time.Time   `json:"created_at"`
	ChildID        pgtype.UUID `json:"child_id"`
	SessionID      pgtype.UUID `json:"session_id"`
}

type InteractionAnalysis struct {
	InteractionID   uuid.UUID `json:"interaction_id"`
	CognitiveArea   string    `json:"cognitive_area"`
	QuestionType    string    `json:"question_type"`
	ComplexityLevel int16     `json:"complexity_level"`
	Sentiment       string    `json:"sentiment"`
	Model           string    `json:"model"`
	AnalyzedAt      time.Time `json:"analyzed_at"`
}

type InteractionTopic struct {
	InteractionID uuid.UUID `json:"interaction_id"`
	TopicID       uuid.UUID `json:"topic_id"`
}

type Recommendation struct {
	ID          uuid.UUID   `json:"id"`
	ChildID     uuid.UUID   `json:"child_id"`
	TopicID     pgtype.UUID `json:"topic_id"`
	Area        string      `json:"area"`
	Title       string      `json:"title"`
	Body        string      `json:"body"`
	Status      string      `json:"status"`
	GeneratedAt time.Time   `json:"generated_at"`
}

type Topic struct {
	ID       uuid.UUID   `json:"id"`
	Slug     string      `json:"slug"`
	Label    string      `json:"label"`
	ParentID pgtype.UUID `json:"parent_id"`
	Area     string      `json:"area"`
}
