// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Development by cognitive area (counts per area).
	AreaBreakdownByChild(ctx context.Context, childID pgtype.UUID) ([]AreaBreakdownByChildRow, error)
	// Deactivate any current assignment for this device, then create the new one.
	// (Run inside a tx with DeactivateDeviceAssignments first.)
	AssignDevice(ctx context.Context, arg AssignDeviceParams) (DeviceAssignment, error)
	BumpChildTopicStat(ctx context.Context, arg BumpChildTopicStatParams) error
	// Days x hours usage for the dashboard heatmap.
	ChildUsageByHour(ctx context.Context, arg ChildUsageByHourParams) ([]ChildUsageByHourRow, error)
	// Bind an unclaimed device to an account and provision its MQTT credentials.
	ClaimDevice(ctx context.Context, arg ClaimDeviceParams) (Device, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateChild(ctx context.Context, arg CreateChildParams) (Child, error)
	CreateInteraction(ctx context.Context, arg CreateInteractionParams) (Interaction, error)
	CreateRecommendation(ctx context.Context, arg CreateRecommendationParams) (Recommendation, error)
	DeactivateDeviceAssignments(ctx context.Context, deviceID uuid.UUID) error
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	// Resolve device -> active child (used by the MQTT ingest for attribution).
	GetActiveChildForDevice(ctx context.Context, deviceID uuid.UUID) (Child, error)
	GetChild(ctx context.Context, id uuid.UUID) (Child, error)
	GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error)
	GetDeviceBySerial(ctx context.Context, serialNumber *string) (Device, error)
	GetInteraction(ctx context.Context, id uuid.UUID) (Interaction, error)
	LinkInteractionTopic(ctx context.Context, arg LinkInteractionTopicParams) error
	// Interest-graph nodes: each topic the child engaged with + frequency.
	ListChildTopicGraph(ctx context.Context, childID uuid.UUID) ([]ListChildTopicGraphRow, error)
	ListChildrenByAccount(ctx context.Context, accountID uuid.UUID) ([]Child, error)
	ListDevicesByAccount(ctx context.Context, accountID pgtype.UUID) ([]Device, error)
	ListInteractionsByChild(ctx context.Context, arg ListInteractionsByChildParams) ([]Interaction, error)
	ListRecommendationsByChild(ctx context.Context, childID uuid.UUID) ([]Recommendation, error)
	// Feeds the analysis worker: interactions without an analysis row yet.
	ListUnanalyzedInteractions(ctx context.Context, limit int32) ([]Interaction, error)
	// Factory provisioning: create an unclaimed device with a serial + activation hash.
	SeedDevice(ctx context.Context, arg SeedDeviceParams) (Device, error)
	TouchDeviceLastSeen(ctx context.Context, id uuid.UUID) error
	UpsertInteractionAnalysis(ctx context.Context, arg UpsertInteractionAnalysisParams) (InteractionAnalysis, error)
	UpsertTopic(ctx context.Context, arg UpsertTopicParams) (Topic, error)
}

var _ Querier = (*Queries)(nil)
